# REST API SPECIFICATION FOR THE ROLLPAY REST API
swagger: "2.0"

info:
  title: Rollpay Rest API
  description: The restful interface for the Rollpay Service
  version: dev mode
produces:
  - application/json
consumes:
  - application/json

schemes:
  - http
  - https

security: []

definitions:

  StandardResponse:
    type: object
    properties:
      message:
        type: string
        readOnly: true

  ############################################
  # Standard Errors
  ############################################
  StandardError:
    type: object
    properties:
      errorCode:
        type: integer
        format: int32
        readOnly: true
      message:
        type: string
        readOnly: true

  FieldError:
    type: object
    properties:
      field:
        type: string
        readOnly: true
        example: "email"
      description:
        type: string
        readOnly: true
        example: "email address is required"

  ValidationError:
    type: object
    properties:
      errorCode:
        type: integer
        format: int32
      message:
        type: string
      errors:
        type: array
        items:
          $ref: "#/definitions/FieldError"

# Global Response Types
responses:
  OkResponse:
    description: operation was successful
    schema:
      $ref: "#/definitions/StandardResponse"

  # ------------
  # Error Responses
  # ------------
  400ErrorResponse:
    description: The provided request was invalid.
    schema:
      $ref: "#/definitions/StandardError"

  401ErrorResponse:
    description: The requested resource requires authentication.
    schema:
      $ref: "#/definitions/StandardError"

  403ErrorResponse:
    description: The request does not contain proper authorization to access this resource.
    schema:
      $ref: "#/definitions/StandardError"

  404ErrorResponse:
    description: The resource requested does not exist.
    schema:
      $ref: "#/definitions/StandardError"

  409ErrorResponse:
    description: A conflict with an existing resource or process occured.
    schema:
      $ref: "#/definitions/StandardError"

  422ErrorResponse:
    description: The request was unprocessable
    schema:
      $ref: "#/definitions/ValidationError"

  500ErrorResponse:
    description: An unexpected system or network error occured.
    schema:
      $ref: "#/definitions/StandardError"

  501ErrorResponse:
    description: The endpoint has not been implemented
    schema:
      $ref: "#/definitions/StandardError"

  503ErrorResponse:
    description: The service is currently not available - please try again
    schema:
      $ref: "#/definitions/StandardError"

  529ErrorResponse:
    description: the reqest limit has been reached - rejecting request
    schema:
      $ref: "#/definitions/StandardError"

paths:
  ##############################################
  # DIAGNOSTIC ENDPOINTS
  ##############################################
  /v1/healthz:
    get:
      tags:
        - Health
      summary: application health check
      operationId: CheckV1
      responses:
        200:
          $ref: "#/responses/OkResponse"
        500:
          $ref: "#/responses/500ErrorResponse"