// Code generated by go-swagger; DO NOT EDIT.

// Package rest Rollpay Rest API
//
//  The restful interface for the Rollpay Service
//  Schemes:
//    http
//    https
//  Host: localhost
//  BasePath: /
//  Version: dev mode
//
//  Consumes:
//    - application/json
//
//  Produces:
//    - application/json
//
// swagger:meta
package rest
