// Code generated by go-swagger; DO NOT EDIT.

package rest

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
)

var (
	// SwaggerJSON embedded version of the swagger document used at generation time
	SwaggerJSON json.RawMessage
	// FlatSwaggerJSON embedded flattened version of the swagger document used at generation time
	FlatSwaggerJSON json.RawMessage
)

func init() {
	SwaggerJSON = json.RawMessage([]byte(`{
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "schemes": [
    "http",
    "https"
  ],
  "swagger": "2.0",
  "info": {
    "description": "The restful interface for the Rollpay Service",
    "title": "Rollpay Rest API",
    "version": "dev mode"
  },
  "paths": {
    "/v1/healthz": {
      "get": {
        "tags": [
          "Health"
        ],
        "summary": "application health check",
        "operationId": "CheckV1",
        "responses": {
          "200": {
            "$ref": "#/responses/OkResponse"
          },
          "500": {
            "$ref": "#/responses/500ErrorResponse"
          }
        }
      }
    }
  },
  "definitions": {
    "FieldError": {
      "type": "object",
      "properties": {
        "description": {
          "type": "string",
          "readOnly": true,
          "example": "email address is required"
        },
        "field": {
          "type": "string",
          "readOnly": true,
          "example": "email"
        }
      }
    },
    "StandardError": {
      "type": "object",
      "properties": {
        "errorCode": {
          "type": "integer",
          "format": "int32",
          "readOnly": true
        },
        "message": {
          "type": "string",
          "readOnly": true
        }
      }
    },
    "StandardResponse": {
      "type": "object",
      "properties": {
        "message": {
          "type": "string",
          "readOnly": true
        }
      }
    },
    "ValidationError": {
      "type": "object",
      "properties": {
        "errorCode": {
          "type": "integer",
          "format": "int32"
        },
        "errors": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/FieldError"
          }
        },
        "message": {
          "type": "string"
        }
      }
    }
  },
  "responses": {
    "400ErrorResponse": {
      "description": "The provided request was invalid.",
      "schema": {
        "$ref": "#/definitions/StandardError"
      }
    },
    "401ErrorResponse": {
      "description": "The requested resource requires authentication.",
      "schema": {
        "$ref": "#/definitions/StandardError"
      }
    },
    "403ErrorResponse": {
      "description": "The request does not contain proper authorization to access this resource.",
      "schema": {
        "$ref": "#/definitions/StandardError"
      }
    },
    "404ErrorResponse": {
      "description": "The resource requested does not exist.",
      "schema": {
        "$ref": "#/definitions/StandardError"
      }
    },
    "409ErrorResponse": {
      "description": "A conflict with an existing resource or process occured.",
      "schema": {
        "$ref": "#/definitions/StandardError"
      }
    },
    "422ErrorResponse": {
      "description": "The request was unprocessable",
      "schema": {
        "$ref": "#/definitions/ValidationError"
      }
    },
    "500ErrorResponse": {
      "description": "An unexpected system or network error occured.",
      "schema": {
        "$ref": "#/definitions/StandardError"
      }
    },
    "501ErrorResponse": {
      "description": "The endpoint has not been implemented",
      "schema": {
        "$ref": "#/definitions/StandardError"
      }
    },
    "503ErrorResponse": {
      "description": "The service is currently not available - please try again",
      "schema": {
        "$ref": "#/definitions/StandardError"
      }
    },
    "529ErrorResponse": {
      "description": "the reqest limit has been reached - rejecting request",
      "schema": {
        "$ref": "#/definitions/StandardError"
      }
    },
    "OkResponse": {
      "description": "operation was successful",
      "schema": {
        "$ref": "#/definitions/StandardResponse"
      }
    }
  }
}`))
	FlatSwaggerJSON = json.RawMessage([]byte(`{
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "schemes": [
    "http",
    "https"
  ],
  "swagger": "2.0",
  "info": {
    "description": "The restful interface for the Rollpay Service",
    "title": "Rollpay Rest API",
    "version": "dev mode"
  },
  "paths": {
    "/v1/healthz": {
      "get": {
        "tags": [
          "Health"
        ],
        "summary": "application health check",
        "operationId": "CheckV1",
        "responses": {
          "200": {
            "description": "operation was successful",
            "schema": {
              "$ref": "#/definitions/StandardResponse"
            }
          },
          "500": {
            "description": "An unexpected system or network error occured.",
            "schema": {
              "$ref": "#/definitions/StandardError"
            }
          }
        }
      }
    }
  },
  "definitions": {
    "FieldError": {
      "type": "object",
      "properties": {
        "description": {
          "type": "string",
          "readOnly": true,
          "example": "email address is required"
        },
        "field": {
          "type": "string",
          "readOnly": true,
          "example": "email"
        }
      }
    },
    "StandardError": {
      "type": "object",
      "properties": {
        "errorCode": {
          "type": "integer",
          "format": "int32",
          "readOnly": true
        },
        "message": {
          "type": "string",
          "readOnly": true
        }
      }
    },
    "StandardResponse": {
      "type": "object",
      "properties": {
        "message": {
          "type": "string",
          "readOnly": true
        }
      }
    },
    "ValidationError": {
      "type": "object",
      "properties": {
        "errorCode": {
          "type": "integer",
          "format": "int32"
        },
        "errors": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/FieldError"
          }
        },
        "message": {
          "type": "string"
        }
      }
    }
  },
  "responses": {
    "400ErrorResponse": {
      "description": "The provided request was invalid.",
      "schema": {
        "$ref": "#/definitions/StandardError"
      }
    },
    "401ErrorResponse": {
      "description": "The requested resource requires authentication.",
      "schema": {
        "$ref": "#/definitions/StandardError"
      }
    },
    "403ErrorResponse": {
      "description": "The request does not contain proper authorization to access this resource.",
      "schema": {
        "$ref": "#/definitions/StandardError"
      }
    },
    "404ErrorResponse": {
      "description": "The resource requested does not exist.",
      "schema": {
        "$ref": "#/definitions/StandardError"
      }
    },
    "409ErrorResponse": {
      "description": "A conflict with an existing resource or process occured.",
      "schema": {
        "$ref": "#/definitions/StandardError"
      }
    },
    "422ErrorResponse": {
      "description": "The request was unprocessable",
      "schema": {
        "$ref": "#/definitions/ValidationError"
      }
    },
    "500ErrorResponse": {
      "description": "An unexpected system or network error occured.",
      "schema": {
        "$ref": "#/definitions/StandardError"
      }
    },
    "501ErrorResponse": {
      "description": "The endpoint has not been implemented",
      "schema": {
        "$ref": "#/definitions/StandardError"
      }
    },
    "503ErrorResponse": {
      "description": "The service is currently not available - please try again",
      "schema": {
        "$ref": "#/definitions/StandardError"
      }
    },
    "529ErrorResponse": {
      "description": "the reqest limit has been reached - rejecting request",
      "schema": {
        "$ref": "#/definitions/StandardError"
      }
    },
    "OkResponse": {
      "description": "operation was successful",
      "schema": {
        "$ref": "#/definitions/StandardResponse"
      }
    }
  }
}`))
}
