// Code generated by go-swagger; DO NOT EDIT.

package health

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// CheckV1HandlerFunc turns a function with the right signature into a check v1 handler
type CheckV1HandlerFunc func(CheckV1Params) middleware.Responder

// Handle executing the request and returning a response
func (fn CheckV1HandlerFunc) Handle(params CheckV1Params) middleware.Responder {
	return fn(params)
}

// CheckV1Handler interface for that can handle valid check v1 params
type CheckV1Handler interface {
	Handle(CheckV1Params) middleware.Responder
}

// NewCheckV1 creates a new http.Handler for the check v1 operation
func NewCheckV1(ctx *middleware.Context, handler CheckV1Handler) *CheckV1 {
	return &CheckV1{Context: ctx, Handler: handler}
}

/* CheckV1 swagger:route GET /v1/healthz Health checkV1

application health check

*/
type CheckV1 struct {
	Context *middleware.Context
	Handler CheckV1Handler
}

func (o *CheckV1) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewCheckV1Params()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
