
-- +migrate Up
CREATE TABLE IF NOT EXISTS users (
    id bigint GENERATED BY DEFAULT AS IDENTITY (START WITH 10000 INCREMENT BY 1) PRIMARY KEY,
    email text NOT NULL CONSTRAINT user_email_uq UNIQUE,
    password text NOT NULL,
    username text NOT NULL,
    avatar bytea NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT ('now'::text)::timestamp with time zone,
    updated_at timestamp with time zone NOT NULL DEFAULT ('now'::text)::timestamp with time zone,
    deleted_at timestamp with time zone NULL
);

CREATE INDEX user_created_at_idx ON users (created_at DESC);
CREATE INDEX user_deleted_at_idx ON users (deleted_at DESC);

-- +migrate Down
DROP INDEX IF EXISTS user_created_at_idx;
DROP INDEX IF EXISTS user_deleted_at_idx;
DROP TABLE IF EXISTS users;
