
-- +migrate Up
CREATE TABLE IF NOT EXISTS organizations (
    id bigint GENERATED BY DEFAULT AS IDENTITY (START WITH 3500 INCREMENT BY 1) PRIMARY KEY,
    name text NOT NULL CONSTRAINT organizations_name_uq UNIQUE,
    logo bytea NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT ('now'::text)::timestamp with time zone,
    updated_at timestamp with time zone NOT NULL DEFAULT ('now'::text)::timestamp with time zone,
    deleted_at timestamp with time zone NULL
);

CREATE INDEX organizations_created_at_idx ON organizations (created_at DESC);
CREATE INDEX organizations_deleted_at_idx ON organizations (deleted_at DESC);
---
CREATE TYPE organization_role AS ENUM ('manager', 'employee');

CREATE TABLE IF NOT EXISTS organization_members (
  user_id bigint NOT NULL REFERENCES users (id),
  organization_id bigint NOT NULL REFERENCES organizations (id),
  role organization_role NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT ('now'::text)::timestamp with time zone,
  updated_at timestamp with time zone NOT NULL DEFAULT ('now'::text)::timestamp with time zone,
  deleted_at timestamp with time zone NULL,
  PRIMARY KEY(user_id, organization_id)
);

CREATE INDEX org_member_role_idx ON organization_members (role);
CREATE INDEX org_member_created_at_idx ON organization_members (created_at DESC);
CREATE INDEX org_member_deleted_at_idx ON organization_members (deleted_at DESC);


-- +migrate Down
DROP INDEX IF EXISTS org_member_role_idx;
DROP INDEX IF EXISTS org_member_created_at_idx;
DROP INDEX IF EXISTS org_member_deleted_at_idx;
DROP TABLE IF EXISTS organization_members;

DROP TYPE IF EXISTS organization_role;

DROP INDEX IF EXISTS organizations_created_at_idx;
DROP INDEX IF EXISTS organizations_deleted_at_idx;
DROP TABLE IF EXISTS organizations;
