// Code generated by SQLBoiler 4.5.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package model

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/friendsofgo/errors"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/sqlboiler/v4/queries"
	"github.com/volatiletech/sqlboiler/v4/queries/qm"
	"github.com/volatiletech/sqlboiler/v4/queries/qmhelper"
	"github.com/volatiletech/strmangle"
)

// OrganizationAccount is an object representing the database table.
type OrganizationAccount struct {
	LinkedAccountID int64 `db:"linked_account_id" boil:"linked_account_id" json:"linked_account_id" toml:"linked_account_id" yaml:"linked_account_id"`
	OrganizationID  int64 `db:"organization_id" boil:"organization_id" json:"organization_id" toml:"organization_id" yaml:"organization_id"`

	R *organizationAccountR `db:"-" boil:"-" json:"-" toml:"-" yaml:"-"`
	L organizationAccountL  `db:"-" boil:"-" json:"-" toml:"-" yaml:"-"`
}

var OrganizationAccountColumns = struct {
	LinkedAccountID string
	OrganizationID  string
}{
	LinkedAccountID: "linked_account_id",
	OrganizationID:  "organization_id",
}

// Generated where

var OrganizationAccountWhere = struct {
	LinkedAccountID whereHelperint64
	OrganizationID  whereHelperint64
}{
	LinkedAccountID: whereHelperint64{field: "\"organization_accounts\".\"linked_account_id\""},
	OrganizationID:  whereHelperint64{field: "\"organization_accounts\".\"organization_id\""},
}

// OrganizationAccountRels is where relationship names are stored.
var OrganizationAccountRels = struct {
	LinkedAccount string
	Organization  string
}{
	LinkedAccount: "LinkedAccount",
	Organization:  "Organization",
}

// organizationAccountR is where relationships are stored.
type organizationAccountR struct {
	LinkedAccount *LinkedAccount `db:"LinkedAccount" boil:"LinkedAccount" json:"LinkedAccount" toml:"LinkedAccount" yaml:"LinkedAccount"`
	Organization  *Organization  `db:"Organization" boil:"Organization" json:"Organization" toml:"Organization" yaml:"Organization"`
}

// NewStruct creates a new relationship struct
func (*organizationAccountR) NewStruct() *organizationAccountR {
	return &organizationAccountR{}
}

// organizationAccountL is where Load methods for each relationship are stored.
type organizationAccountL struct{}

var (
	organizationAccountAllColumns            = []string{"linked_account_id", "organization_id"}
	organizationAccountColumnsWithoutDefault = []string{"linked_account_id", "organization_id"}
	organizationAccountColumnsWithDefault    = []string{}
	organizationAccountPrimaryKeyColumns     = []string{"linked_account_id"}
)

type (
	// OrganizationAccountSlice is an alias for a slice of pointers to OrganizationAccount.
	// This should generally be used opposed to []OrganizationAccount.
	OrganizationAccountSlice []*OrganizationAccount

	organizationAccountQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	organizationAccountType                 = reflect.TypeOf(&OrganizationAccount{})
	organizationAccountMapping              = queries.MakeStructMapping(organizationAccountType)
	organizationAccountPrimaryKeyMapping, _ = queries.BindMapping(organizationAccountType, organizationAccountMapping, organizationAccountPrimaryKeyColumns)
	organizationAccountInsertCacheMut       sync.RWMutex
	organizationAccountInsertCache          = make(map[string]insertCache)
	organizationAccountUpdateCacheMut       sync.RWMutex
	organizationAccountUpdateCache          = make(map[string]updateCache)
	organizationAccountUpsertCacheMut       sync.RWMutex
	organizationAccountUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

// One returns a single organizationAccount record from the query.
func (q organizationAccountQuery) One(ctx context.Context, exec boil.ContextExecutor) (*OrganizationAccount, error) {
	o := &OrganizationAccount{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Cause(err) == sql.ErrNoRows {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "model: failed to execute a one query for organization_accounts")
	}

	return o, nil
}

// All returns all OrganizationAccount records from the query.
func (q organizationAccountQuery) All(ctx context.Context, exec boil.ContextExecutor) (OrganizationAccountSlice, error) {
	var o []*OrganizationAccount

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "model: failed to assign all query results to OrganizationAccount slice")
	}

	return o, nil
}

// Count returns the count of all OrganizationAccount records in the query.
func (q organizationAccountQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "model: failed to count organization_accounts rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table.
func (q organizationAccountQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "model: failed to check if organization_accounts exists")
	}

	return count > 0, nil
}

// LinkedAccount pointed to by the foreign key.
func (o *OrganizationAccount) LinkedAccount(mods ...qm.QueryMod) linkedAccountQuery {
	queryMods := []qm.QueryMod{
		qm.Where("\"id\" = ?", o.LinkedAccountID),
		qmhelper.WhereIsNull("deleted_at"),
	}

	queryMods = append(queryMods, mods...)

	query := LinkedAccounts(queryMods...)
	queries.SetFrom(query.Query, "\"linked_accounts\"")

	return query
}

// Organization pointed to by the foreign key.
func (o *OrganizationAccount) Organization(mods ...qm.QueryMod) organizationQuery {
	queryMods := []qm.QueryMod{
		qm.Where("\"id\" = ?", o.OrganizationID),
		qmhelper.WhereIsNull("deleted_at"),
	}

	queryMods = append(queryMods, mods...)

	query := Organizations(queryMods...)
	queries.SetFrom(query.Query, "\"organizations\"")

	return query
}

// LoadLinkedAccount allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (organizationAccountL) LoadLinkedAccount(ctx context.Context, e boil.ContextExecutor, singular bool, maybeOrganizationAccount interface{}, mods queries.Applicator) error {
	var slice []*OrganizationAccount
	var object *OrganizationAccount

	if singular {
		object = maybeOrganizationAccount.(*OrganizationAccount)
	} else {
		slice = *maybeOrganizationAccount.(*[]*OrganizationAccount)
	}

	args := make([]interface{}, 0, 1)
	if singular {
		if object.R == nil {
			object.R = &organizationAccountR{}
		}
		args = append(args, object.LinkedAccountID)

	} else {
	Outer:
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &organizationAccountR{}
			}

			for _, a := range args {
				if a == obj.LinkedAccountID {
					continue Outer
				}
			}

			args = append(args, obj.LinkedAccountID)

		}
	}

	if len(args) == 0 {
		return nil
	}

	query := NewQuery(
		qm.From(`linked_accounts`),
		qm.WhereIn(`linked_accounts.id in ?`, args...),
		qmhelper.WhereIsNull(`linked_accounts.deleted_at`),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load LinkedAccount")
	}

	var resultSlice []*LinkedAccount
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice LinkedAccount")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for linked_accounts")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for linked_accounts")
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.LinkedAccount = foreign
		if foreign.R == nil {
			foreign.R = &linkedAccountR{}
		}
		foreign.R.OrganizationAccount = object
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if local.LinkedAccountID == foreign.ID {
				local.R.LinkedAccount = foreign
				if foreign.R == nil {
					foreign.R = &linkedAccountR{}
				}
				foreign.R.OrganizationAccount = local
				break
			}
		}
	}

	return nil
}

// LoadOrganization allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (organizationAccountL) LoadOrganization(ctx context.Context, e boil.ContextExecutor, singular bool, maybeOrganizationAccount interface{}, mods queries.Applicator) error {
	var slice []*OrganizationAccount
	var object *OrganizationAccount

	if singular {
		object = maybeOrganizationAccount.(*OrganizationAccount)
	} else {
		slice = *maybeOrganizationAccount.(*[]*OrganizationAccount)
	}

	args := make([]interface{}, 0, 1)
	if singular {
		if object.R == nil {
			object.R = &organizationAccountR{}
		}
		args = append(args, object.OrganizationID)

	} else {
	Outer:
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &organizationAccountR{}
			}

			for _, a := range args {
				if a == obj.OrganizationID {
					continue Outer
				}
			}

			args = append(args, obj.OrganizationID)

		}
	}

	if len(args) == 0 {
		return nil
	}

	query := NewQuery(
		qm.From(`organizations`),
		qm.WhereIn(`organizations.id in ?`, args...),
		qmhelper.WhereIsNull(`organizations.deleted_at`),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load Organization")
	}

	var resultSlice []*Organization
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice Organization")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for organizations")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for organizations")
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.Organization = foreign
		if foreign.R == nil {
			foreign.R = &organizationR{}
		}
		foreign.R.OrganizationAccounts = append(foreign.R.OrganizationAccounts, object)
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if local.OrganizationID == foreign.ID {
				local.R.Organization = foreign
				if foreign.R == nil {
					foreign.R = &organizationR{}
				}
				foreign.R.OrganizationAccounts = append(foreign.R.OrganizationAccounts, local)
				break
			}
		}
	}

	return nil
}

// SetLinkedAccount of the organizationAccount to the related item.
// Sets o.R.LinkedAccount to related.
// Adds o to related.R.OrganizationAccount.
func (o *OrganizationAccount) SetLinkedAccount(ctx context.Context, exec boil.ContextExecutor, insert bool, related *LinkedAccount) error {
	var err error
	if insert {
		if err = related.Insert(ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE \"organization_accounts\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, []string{"linked_account_id"}),
		strmangle.WhereClause("\"", "\"", 2, organizationAccountPrimaryKeyColumns),
	)
	values := []interface{}{related.ID, o.LinkedAccountID}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, updateQuery)
		fmt.Fprintln(writer, values)
	}
	if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	o.LinkedAccountID = related.ID
	if o.R == nil {
		o.R = &organizationAccountR{
			LinkedAccount: related,
		}
	} else {
		o.R.LinkedAccount = related
	}

	if related.R == nil {
		related.R = &linkedAccountR{
			OrganizationAccount: o,
		}
	} else {
		related.R.OrganizationAccount = o
	}

	return nil
}

// SetOrganization of the organizationAccount to the related item.
// Sets o.R.Organization to related.
// Adds o to related.R.OrganizationAccounts.
func (o *OrganizationAccount) SetOrganization(ctx context.Context, exec boil.ContextExecutor, insert bool, related *Organization) error {
	var err error
	if insert {
		if err = related.Insert(ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE \"organization_accounts\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, []string{"organization_id"}),
		strmangle.WhereClause("\"", "\"", 2, organizationAccountPrimaryKeyColumns),
	)
	values := []interface{}{related.ID, o.LinkedAccountID}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, updateQuery)
		fmt.Fprintln(writer, values)
	}
	if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	o.OrganizationID = related.ID
	if o.R == nil {
		o.R = &organizationAccountR{
			Organization: related,
		}
	} else {
		o.R.Organization = related
	}

	if related.R == nil {
		related.R = &organizationR{
			OrganizationAccounts: OrganizationAccountSlice{o},
		}
	} else {
		related.R.OrganizationAccounts = append(related.R.OrganizationAccounts, o)
	}

	return nil
}

// OrganizationAccounts retrieves all the records using an executor.
func OrganizationAccounts(mods ...qm.QueryMod) organizationAccountQuery {
	mods = append(mods, qm.From("\"organization_accounts\""))
	return organizationAccountQuery{NewQuery(mods...)}
}

// FindOrganizationAccount retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindOrganizationAccount(ctx context.Context, exec boil.ContextExecutor, linkedAccountID int64, selectCols ...string) (*OrganizationAccount, error) {
	organizationAccountObj := &OrganizationAccount{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from \"organization_accounts\" where \"linked_account_id\"=$1", sel,
	)

	q := queries.Raw(query, linkedAccountID)

	err := q.Bind(ctx, exec, organizationAccountObj)
	if err != nil {
		if errors.Cause(err) == sql.ErrNoRows {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "model: unable to select from organization_accounts")
	}

	return organizationAccountObj, nil
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *OrganizationAccount) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("model: no organization_accounts provided for insertion")
	}

	var err error

	nzDefaults := queries.NonZeroDefaultSet(organizationAccountColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	organizationAccountInsertCacheMut.RLock()
	cache, cached := organizationAccountInsertCache[key]
	organizationAccountInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			organizationAccountAllColumns,
			organizationAccountColumnsWithDefault,
			organizationAccountColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(organizationAccountType, organizationAccountMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(organizationAccountType, organizationAccountMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO \"organization_accounts\" (\"%s\") %%sVALUES (%s)%%s", strings.Join(wl, "\",\""), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO \"organization_accounts\" %sDEFAULT VALUES%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			queryReturning = fmt.Sprintf(" RETURNING \"%s\"", strings.Join(returnColumns, "\",\""))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}

	if err != nil {
		return errors.Wrap(err, "model: unable to insert into organization_accounts")
	}

	if !cached {
		organizationAccountInsertCacheMut.Lock()
		organizationAccountInsertCache[key] = cache
		organizationAccountInsertCacheMut.Unlock()
	}

	return nil
}

// Update uses an executor to update the OrganizationAccount.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *OrganizationAccount) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	var err error
	key := makeCacheKey(columns, nil)
	organizationAccountUpdateCacheMut.RLock()
	cache, cached := organizationAccountUpdateCache[key]
	organizationAccountUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			organizationAccountAllColumns,
			organizationAccountPrimaryKeyColumns,
		)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("model: unable to update organization_accounts, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE \"organization_accounts\" SET %s WHERE %s",
			strmangle.SetParamNames("\"", "\"", 1, wl),
			strmangle.WhereClause("\"", "\"", len(wl)+1, organizationAccountPrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(organizationAccountType, organizationAccountMapping, append(wl, organizationAccountPrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "model: unable to update organization_accounts row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "model: failed to get rows affected by update for organization_accounts")
	}

	if !cached {
		organizationAccountUpdateCacheMut.Lock()
		organizationAccountUpdateCache[key] = cache
		organizationAccountUpdateCacheMut.Unlock()
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values.
func (q organizationAccountQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "model: unable to update all for organization_accounts")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "model: unable to retrieve rows affected for organization_accounts")
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o OrganizationAccountSlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("model: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), organizationAccountPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE \"organization_accounts\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), len(colNames)+1, organizationAccountPrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "model: unable to update all in organizationAccount slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "model: unable to retrieve rows affected all in update all organizationAccount")
	}
	return rowsAff, nil
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *OrganizationAccount) Upsert(ctx context.Context, exec boil.ContextExecutor, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns) error {
	if o == nil {
		return errors.New("model: no organization_accounts provided for upsert")
	}

	nzDefaults := queries.NonZeroDefaultSet(organizationAccountColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	if updateOnConflict {
		buf.WriteByte('t')
	} else {
		buf.WriteByte('f')
	}
	buf.WriteByte('.')
	for _, c := range conflictColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	organizationAccountUpsertCacheMut.RLock()
	cache, cached := organizationAccountUpsertCache[key]
	organizationAccountUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, ret := insertColumns.InsertColumnSet(
			organizationAccountAllColumns,
			organizationAccountColumnsWithDefault,
			organizationAccountColumnsWithoutDefault,
			nzDefaults,
		)
		update := updateColumns.UpdateColumnSet(
			organizationAccountAllColumns,
			organizationAccountPrimaryKeyColumns,
		)

		if updateOnConflict && len(update) == 0 {
			return errors.New("model: unable to upsert organization_accounts, could not build update column list")
		}

		conflict := conflictColumns
		if len(conflict) == 0 {
			conflict = make([]string, len(organizationAccountPrimaryKeyColumns))
			copy(conflict, organizationAccountPrimaryKeyColumns)
		}
		cache.query = buildUpsertQueryPostgres(dialect, "\"organization_accounts\"", updateOnConflict, ret, update, conflict, insert)

		cache.valueMapping, err = queries.BindMapping(organizationAccountType, organizationAccountMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(organizationAccountType, organizationAccountMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(returns...)
		if err == sql.ErrNoRows {
			err = nil // Postgres doesn't return anything when there's no update
		}
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}
	if err != nil {
		return errors.Wrap(err, "model: unable to upsert organization_accounts")
	}

	if !cached {
		organizationAccountUpsertCacheMut.Lock()
		organizationAccountUpsertCache[key] = cache
		organizationAccountUpsertCacheMut.Unlock()
	}

	return nil
}

// Delete deletes a single OrganizationAccount record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *OrganizationAccount) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("model: no OrganizationAccount provided for delete")
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), organizationAccountPrimaryKeyMapping)
	sql := "DELETE FROM \"organization_accounts\" WHERE \"linked_account_id\"=$1"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "model: unable to delete from organization_accounts")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "model: failed to get rows affected by delete for organization_accounts")
	}

	return rowsAff, nil
}

// DeleteAll deletes all matching rows.
func (q organizationAccountQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("model: no organizationAccountQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "model: unable to delete all from organization_accounts")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "model: failed to get rows affected by deleteall for organization_accounts")
	}

	return rowsAff, nil
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o OrganizationAccountSlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	var args []interface{}
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), organizationAccountPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM \"organization_accounts\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, organizationAccountPrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "model: unable to delete all from organizationAccount slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "model: failed to get rows affected by deleteall for organization_accounts")
	}

	return rowsAff, nil
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *OrganizationAccount) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindOrganizationAccount(ctx, exec, o.LinkedAccountID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *OrganizationAccountSlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := OrganizationAccountSlice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), organizationAccountPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT \"organization_accounts\".* FROM \"organization_accounts\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, organizationAccountPrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "model: unable to reload all in OrganizationAccountSlice")
	}

	*o = slice

	return nil
}

// OrganizationAccountExists checks if the OrganizationAccount row exists.
func OrganizationAccountExists(ctx context.Context, exec boil.ContextExecutor, linkedAccountID int64) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from \"organization_accounts\" where \"linked_account_id\"=$1 limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, linkedAccountID)
	}
	row := exec.QueryRowContext(ctx, sql, linkedAccountID)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "model: unable to check if organization_accounts exists")
	}

	return exists, nil
}
