// Code generated by SQLBoiler 4.5.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package model

import "testing"

func TestUpsert(t *testing.T) {
	t.Run("LinkedAccounts", testLinkedAccountsUpsert)

	t.Run("OrganizationAccounts", testOrganizationAccountsUpsert)

	t.Run("OrganizationMembers", testOrganizationMembersUpsert)

	t.Run("Organizations", testOrganizationsUpsert)

	t.Run("UserAccounts", testUserAccountsUpsert)

	t.Run("Users", testUsersUpsert)
}
