// Code generated by go-swagger; DO NOT EDIT.

package user

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/syllabix/rollpay/backend/api/model"
)

// CreateUserV1CreatedCode is the HTTP code returned for type CreateUserV1Created
const CreateUserV1CreatedCode int = 201

/*CreateUserV1Created a newly created user

swagger:response createUserV1Created
*/
type CreateUserV1Created struct {

	/*
	  In: Body
	*/
	Payload *model.User `json:"body,omitempty"`
}

// NewCreateUserV1Created creates CreateUserV1Created with default headers values
func NewCreateUserV1Created() *CreateUserV1Created {

	return &CreateUserV1Created{}
}

// WithPayload adds the payload to the create user v1 created response
func (o *CreateUserV1Created) WithPayload(payload *model.User) *CreateUserV1Created {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the create user v1 created response
func (o *CreateUserV1Created) SetPayload(payload *model.User) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *CreateUserV1Created) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(201)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// CreateUserV1BadRequestCode is the HTTP code returned for type CreateUserV1BadRequest
const CreateUserV1BadRequestCode int = 400

/*CreateUserV1BadRequest The provided request was invalid.

swagger:response createUserV1BadRequest
*/
type CreateUserV1BadRequest struct {

	/*
	  In: Body
	*/
	Payload *model.StandardError `json:"body,omitempty"`
}

// NewCreateUserV1BadRequest creates CreateUserV1BadRequest with default headers values
func NewCreateUserV1BadRequest() *CreateUserV1BadRequest {

	return &CreateUserV1BadRequest{}
}

// WithPayload adds the payload to the create user v1 bad request response
func (o *CreateUserV1BadRequest) WithPayload(payload *model.StandardError) *CreateUserV1BadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the create user v1 bad request response
func (o *CreateUserV1BadRequest) SetPayload(payload *model.StandardError) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *CreateUserV1BadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// CreateUserV1ConflictCode is the HTTP code returned for type CreateUserV1Conflict
const CreateUserV1ConflictCode int = 409

/*CreateUserV1Conflict A conflict with an existing resource or process occured.

swagger:response createUserV1Conflict
*/
type CreateUserV1Conflict struct {

	/*
	  In: Body
	*/
	Payload *model.StandardError `json:"body,omitempty"`
}

// NewCreateUserV1Conflict creates CreateUserV1Conflict with default headers values
func NewCreateUserV1Conflict() *CreateUserV1Conflict {

	return &CreateUserV1Conflict{}
}

// WithPayload adds the payload to the create user v1 conflict response
func (o *CreateUserV1Conflict) WithPayload(payload *model.StandardError) *CreateUserV1Conflict {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the create user v1 conflict response
func (o *CreateUserV1Conflict) SetPayload(payload *model.StandardError) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *CreateUserV1Conflict) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(409)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// CreateUserV1InternalServerErrorCode is the HTTP code returned for type CreateUserV1InternalServerError
const CreateUserV1InternalServerErrorCode int = 500

/*CreateUserV1InternalServerError An unexpected system or network error occured.

swagger:response createUserV1InternalServerError
*/
type CreateUserV1InternalServerError struct {

	/*
	  In: Body
	*/
	Payload *model.StandardError `json:"body,omitempty"`
}

// NewCreateUserV1InternalServerError creates CreateUserV1InternalServerError with default headers values
func NewCreateUserV1InternalServerError() *CreateUserV1InternalServerError {

	return &CreateUserV1InternalServerError{}
}

// WithPayload adds the payload to the create user v1 internal server error response
func (o *CreateUserV1InternalServerError) WithPayload(payload *model.StandardError) *CreateUserV1InternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the create user v1 internal server error response
func (o *CreateUserV1InternalServerError) SetPayload(payload *model.StandardError) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *CreateUserV1InternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
