// Code generated by go-swagger; DO NOT EDIT.

package user

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"

	"github.com/syllabix/rollpay/backend/api/model"
)

// DeleteUserByIDV1HandlerFunc turns a function with the right signature into a delete user by ID v1 handler
type DeleteUserByIDV1HandlerFunc func(DeleteUserByIDV1Params, *model.Principal) middleware.Responder

// Handle executing the request and returning a response
func (fn DeleteUserByIDV1HandlerFunc) Handle(params DeleteUserByIDV1Params, principal *model.Principal) middleware.Responder {
	return fn(params, principal)
}

// DeleteUserByIDV1Handler interface for that can handle valid delete user by ID v1 params
type DeleteUserByIDV1Handler interface {
	Handle(DeleteUserByIDV1Params, *model.Principal) middleware.Responder
}

// NewDeleteUserByIDV1 creates a new http.Handler for the delete user by ID v1 operation
func NewDeleteUserByIDV1(ctx *middleware.Context, handler DeleteUserByIDV1Handler) *DeleteUserByIDV1 {
	return &DeleteUserByIDV1{Context: ctx, Handler: handler}
}

/* DeleteUserByIDV1 swagger:route DELETE /v1/user/{id} User deleteUserByIdV1

delete a user by id

*/
type DeleteUserByIDV1 struct {
	Context *middleware.Context
	Handler DeleteUserByIDV1Handler
}

func (o *DeleteUserByIDV1) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewDeleteUserByIDV1Params()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal *model.Principal
	if uprinc != nil {
		principal = uprinc.(*model.Principal) // this is really a model.Principal, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
