// Code generated by go-swagger; DO NOT EDIT.

package user

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/syllabix/rollpay/backend/api/model"
)

// DeleteUserByIDV1OKCode is the HTTP code returned for type DeleteUserByIDV1OK
const DeleteUserByIDV1OKCode int = 200

/*DeleteUserByIDV1OK operation was successful

swagger:response deleteUserByIdV1OK
*/
type DeleteUserByIDV1OK struct {

	/*
	  In: Body
	*/
	Payload *model.StandardResponse `json:"body,omitempty"`
}

// NewDeleteUserByIDV1OK creates DeleteUserByIDV1OK with default headers values
func NewDeleteUserByIDV1OK() *DeleteUserByIDV1OK {

	return &DeleteUserByIDV1OK{}
}

// WithPayload adds the payload to the delete user by Id v1 o k response
func (o *DeleteUserByIDV1OK) WithPayload(payload *model.StandardResponse) *DeleteUserByIDV1OK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete user by Id v1 o k response
func (o *DeleteUserByIDV1OK) SetPayload(payload *model.StandardResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteUserByIDV1OK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// DeleteUserByIDV1BadRequestCode is the HTTP code returned for type DeleteUserByIDV1BadRequest
const DeleteUserByIDV1BadRequestCode int = 400

/*DeleteUserByIDV1BadRequest The provided request was invalid.

swagger:response deleteUserByIdV1BadRequest
*/
type DeleteUserByIDV1BadRequest struct {

	/*
	  In: Body
	*/
	Payload *model.StandardError `json:"body,omitempty"`
}

// NewDeleteUserByIDV1BadRequest creates DeleteUserByIDV1BadRequest with default headers values
func NewDeleteUserByIDV1BadRequest() *DeleteUserByIDV1BadRequest {

	return &DeleteUserByIDV1BadRequest{}
}

// WithPayload adds the payload to the delete user by Id v1 bad request response
func (o *DeleteUserByIDV1BadRequest) WithPayload(payload *model.StandardError) *DeleteUserByIDV1BadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete user by Id v1 bad request response
func (o *DeleteUserByIDV1BadRequest) SetPayload(payload *model.StandardError) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteUserByIDV1BadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// DeleteUserByIDV1NotFoundCode is the HTTP code returned for type DeleteUserByIDV1NotFound
const DeleteUserByIDV1NotFoundCode int = 404

/*DeleteUserByIDV1NotFound The resource requested does not exist.

swagger:response deleteUserByIdV1NotFound
*/
type DeleteUserByIDV1NotFound struct {

	/*
	  In: Body
	*/
	Payload *model.StandardError `json:"body,omitempty"`
}

// NewDeleteUserByIDV1NotFound creates DeleteUserByIDV1NotFound with default headers values
func NewDeleteUserByIDV1NotFound() *DeleteUserByIDV1NotFound {

	return &DeleteUserByIDV1NotFound{}
}

// WithPayload adds the payload to the delete user by Id v1 not found response
func (o *DeleteUserByIDV1NotFound) WithPayload(payload *model.StandardError) *DeleteUserByIDV1NotFound {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete user by Id v1 not found response
func (o *DeleteUserByIDV1NotFound) SetPayload(payload *model.StandardError) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteUserByIDV1NotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// DeleteUserByIDV1InternalServerErrorCode is the HTTP code returned for type DeleteUserByIDV1InternalServerError
const DeleteUserByIDV1InternalServerErrorCode int = 500

/*DeleteUserByIDV1InternalServerError An unexpected system or network error occured.

swagger:response deleteUserByIdV1InternalServerError
*/
type DeleteUserByIDV1InternalServerError struct {

	/*
	  In: Body
	*/
	Payload *model.StandardError `json:"body,omitempty"`
}

// NewDeleteUserByIDV1InternalServerError creates DeleteUserByIDV1InternalServerError with default headers values
func NewDeleteUserByIDV1InternalServerError() *DeleteUserByIDV1InternalServerError {

	return &DeleteUserByIDV1InternalServerError{}
}

// WithPayload adds the payload to the delete user by Id v1 internal server error response
func (o *DeleteUserByIDV1InternalServerError) WithPayload(payload *model.StandardError) *DeleteUserByIDV1InternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete user by Id v1 internal server error response
func (o *DeleteUserByIDV1InternalServerError) SetPayload(payload *model.StandardError) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteUserByIDV1InternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
