// Code generated by go-swagger; DO NOT EDIT.

package model

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// FieldError field error
//
// swagger:model FieldError
type FieldError struct {

	// description
	// Example: email address is required
	// Read Only: true
	Description string `json:"description,omitempty"`

	// field
	// Example: email
	// Read Only: true
	Field string `json:"field,omitempty"`
}

// Validate validates this field error
func (m *FieldError) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validate this field error based on the context it is used
func (m *FieldError) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateDescription(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateField(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *FieldError) contextValidateDescription(ctx context.Context, formats strfmt.Registry) error {

	if err := validate.ReadOnly(ctx, "description", "body", string(m.Description)); err != nil {
		return err
	}

	return nil
}

func (m *FieldError) contextValidateField(ctx context.Context, formats strfmt.Registry) error {

	if err := validate.ReadOnly(ctx, "field", "body", string(m.Field)); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *FieldError) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *FieldError) UnmarshalBinary(b []byte) error {
	var res FieldError
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
