// Code generated by go-swagger; DO NOT EDIT.

package organization

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/syllabix/rollpay/backend/api/model"
)

// GetOrgMembersV1OKCode is the HTTP code returned for type GetOrgMembersV1OK
const GetOrgMembersV1OKCode int = 200

/*GetOrgMembersV1OK a list of organization memebers

swagger:response getOrgMembersV1OK
*/
type GetOrgMembersV1OK struct {

	/*
	  In: Body
	*/
	Payload *model.MemberList `json:"body,omitempty"`
}

// NewGetOrgMembersV1OK creates GetOrgMembersV1OK with default headers values
func NewGetOrgMembersV1OK() *GetOrgMembersV1OK {

	return &GetOrgMembersV1OK{}
}

// WithPayload adds the payload to the get org members v1 o k response
func (o *GetOrgMembersV1OK) WithPayload(payload *model.MemberList) *GetOrgMembersV1OK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get org members v1 o k response
func (o *GetOrgMembersV1OK) SetPayload(payload *model.MemberList) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetOrgMembersV1OK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetOrgMembersV1BadRequestCode is the HTTP code returned for type GetOrgMembersV1BadRequest
const GetOrgMembersV1BadRequestCode int = 400

/*GetOrgMembersV1BadRequest The provided request was invalid.

swagger:response getOrgMembersV1BadRequest
*/
type GetOrgMembersV1BadRequest struct {

	/*
	  In: Body
	*/
	Payload *model.StandardError `json:"body,omitempty"`
}

// NewGetOrgMembersV1BadRequest creates GetOrgMembersV1BadRequest with default headers values
func NewGetOrgMembersV1BadRequest() *GetOrgMembersV1BadRequest {

	return &GetOrgMembersV1BadRequest{}
}

// WithPayload adds the payload to the get org members v1 bad request response
func (o *GetOrgMembersV1BadRequest) WithPayload(payload *model.StandardError) *GetOrgMembersV1BadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get org members v1 bad request response
func (o *GetOrgMembersV1BadRequest) SetPayload(payload *model.StandardError) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetOrgMembersV1BadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetOrgMembersV1NotFoundCode is the HTTP code returned for type GetOrgMembersV1NotFound
const GetOrgMembersV1NotFoundCode int = 404

/*GetOrgMembersV1NotFound The resource requested does not exist.

swagger:response getOrgMembersV1NotFound
*/
type GetOrgMembersV1NotFound struct {

	/*
	  In: Body
	*/
	Payload *model.StandardError `json:"body,omitempty"`
}

// NewGetOrgMembersV1NotFound creates GetOrgMembersV1NotFound with default headers values
func NewGetOrgMembersV1NotFound() *GetOrgMembersV1NotFound {

	return &GetOrgMembersV1NotFound{}
}

// WithPayload adds the payload to the get org members v1 not found response
func (o *GetOrgMembersV1NotFound) WithPayload(payload *model.StandardError) *GetOrgMembersV1NotFound {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get org members v1 not found response
func (o *GetOrgMembersV1NotFound) SetPayload(payload *model.StandardError) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetOrgMembersV1NotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetOrgMembersV1InternalServerErrorCode is the HTTP code returned for type GetOrgMembersV1InternalServerError
const GetOrgMembersV1InternalServerErrorCode int = 500

/*GetOrgMembersV1InternalServerError An unexpected system or network error occured.

swagger:response getOrgMembersV1InternalServerError
*/
type GetOrgMembersV1InternalServerError struct {

	/*
	  In: Body
	*/
	Payload *model.StandardError `json:"body,omitempty"`
}

// NewGetOrgMembersV1InternalServerError creates GetOrgMembersV1InternalServerError with default headers values
func NewGetOrgMembersV1InternalServerError() *GetOrgMembersV1InternalServerError {

	return &GetOrgMembersV1InternalServerError{}
}

// WithPayload adds the payload to the get org members v1 internal server error response
func (o *GetOrgMembersV1InternalServerError) WithPayload(payload *model.StandardError) *GetOrgMembersV1InternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get org members v1 internal server error response
func (o *GetOrgMembersV1InternalServerError) SetPayload(payload *model.StandardError) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetOrgMembersV1InternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
