// Code generated by go-swagger; DO NOT EDIT.

package organization

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/syllabix/rollpay/backend/api/model"
)

// GetOrganizationByIDV1OKCode is the HTTP code returned for type GetOrganizationByIDV1OK
const GetOrganizationByIDV1OKCode int = 200

/*GetOrganizationByIDV1OK a

swagger:response getOrganizationByIdV1OK
*/
type GetOrganizationByIDV1OK struct {

	/*
	  In: Body
	*/
	Payload *model.Organization `json:"body,omitempty"`
}

// NewGetOrganizationByIDV1OK creates GetOrganizationByIDV1OK with default headers values
func NewGetOrganizationByIDV1OK() *GetOrganizationByIDV1OK {

	return &GetOrganizationByIDV1OK{}
}

// WithPayload adds the payload to the get organization by Id v1 o k response
func (o *GetOrganizationByIDV1OK) WithPayload(payload *model.Organization) *GetOrganizationByIDV1OK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get organization by Id v1 o k response
func (o *GetOrganizationByIDV1OK) SetPayload(payload *model.Organization) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetOrganizationByIDV1OK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetOrganizationByIDV1BadRequestCode is the HTTP code returned for type GetOrganizationByIDV1BadRequest
const GetOrganizationByIDV1BadRequestCode int = 400

/*GetOrganizationByIDV1BadRequest The provided request was invalid.

swagger:response getOrganizationByIdV1BadRequest
*/
type GetOrganizationByIDV1BadRequest struct {

	/*
	  In: Body
	*/
	Payload *model.StandardError `json:"body,omitempty"`
}

// NewGetOrganizationByIDV1BadRequest creates GetOrganizationByIDV1BadRequest with default headers values
func NewGetOrganizationByIDV1BadRequest() *GetOrganizationByIDV1BadRequest {

	return &GetOrganizationByIDV1BadRequest{}
}

// WithPayload adds the payload to the get organization by Id v1 bad request response
func (o *GetOrganizationByIDV1BadRequest) WithPayload(payload *model.StandardError) *GetOrganizationByIDV1BadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get organization by Id v1 bad request response
func (o *GetOrganizationByIDV1BadRequest) SetPayload(payload *model.StandardError) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetOrganizationByIDV1BadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetOrganizationByIDV1UnauthorizedCode is the HTTP code returned for type GetOrganizationByIDV1Unauthorized
const GetOrganizationByIDV1UnauthorizedCode int = 401

/*GetOrganizationByIDV1Unauthorized The requested resource requires authentication.

swagger:response getOrganizationByIdV1Unauthorized
*/
type GetOrganizationByIDV1Unauthorized struct {

	/*
	  In: Body
	*/
	Payload *model.StandardError `json:"body,omitempty"`
}

// NewGetOrganizationByIDV1Unauthorized creates GetOrganizationByIDV1Unauthorized with default headers values
func NewGetOrganizationByIDV1Unauthorized() *GetOrganizationByIDV1Unauthorized {

	return &GetOrganizationByIDV1Unauthorized{}
}

// WithPayload adds the payload to the get organization by Id v1 unauthorized response
func (o *GetOrganizationByIDV1Unauthorized) WithPayload(payload *model.StandardError) *GetOrganizationByIDV1Unauthorized {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get organization by Id v1 unauthorized response
func (o *GetOrganizationByIDV1Unauthorized) SetPayload(payload *model.StandardError) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetOrganizationByIDV1Unauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(401)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetOrganizationByIDV1NotFoundCode is the HTTP code returned for type GetOrganizationByIDV1NotFound
const GetOrganizationByIDV1NotFoundCode int = 404

/*GetOrganizationByIDV1NotFound The resource requested does not exist.

swagger:response getOrganizationByIdV1NotFound
*/
type GetOrganizationByIDV1NotFound struct {

	/*
	  In: Body
	*/
	Payload *model.StandardError `json:"body,omitempty"`
}

// NewGetOrganizationByIDV1NotFound creates GetOrganizationByIDV1NotFound with default headers values
func NewGetOrganizationByIDV1NotFound() *GetOrganizationByIDV1NotFound {

	return &GetOrganizationByIDV1NotFound{}
}

// WithPayload adds the payload to the get organization by Id v1 not found response
func (o *GetOrganizationByIDV1NotFound) WithPayload(payload *model.StandardError) *GetOrganizationByIDV1NotFound {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get organization by Id v1 not found response
func (o *GetOrganizationByIDV1NotFound) SetPayload(payload *model.StandardError) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetOrganizationByIDV1NotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetOrganizationByIDV1InternalServerErrorCode is the HTTP code returned for type GetOrganizationByIDV1InternalServerError
const GetOrganizationByIDV1InternalServerErrorCode int = 500

/*GetOrganizationByIDV1InternalServerError An unexpected system or network error occured.

swagger:response getOrganizationByIdV1InternalServerError
*/
type GetOrganizationByIDV1InternalServerError struct {

	/*
	  In: Body
	*/
	Payload *model.StandardError `json:"body,omitempty"`
}

// NewGetOrganizationByIDV1InternalServerError creates GetOrganizationByIDV1InternalServerError with default headers values
func NewGetOrganizationByIDV1InternalServerError() *GetOrganizationByIDV1InternalServerError {

	return &GetOrganizationByIDV1InternalServerError{}
}

// WithPayload adds the payload to the get organization by Id v1 internal server error response
func (o *GetOrganizationByIDV1InternalServerError) WithPayload(payload *model.StandardError) *GetOrganizationByIDV1InternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get organization by Id v1 internal server error response
func (o *GetOrganizationByIDV1InternalServerError) SetPayload(payload *model.StandardError) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetOrganizationByIDV1InternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
