// Code generated by go-swagger; DO NOT EDIT.

package organization

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/syllabix/rollpay/backend/api/model"
)

// GetAllOrgsV1OKCode is the HTTP code returned for type GetAllOrgsV1OK
const GetAllOrgsV1OKCode int = 200

/*GetAllOrgsV1OK a list of available organizations

swagger:response getAllOrgsV1OK
*/
type GetAllOrgsV1OK struct {

	/*
	  In: Body
	*/
	Payload *model.OrganizationList `json:"body,omitempty"`
}

// NewGetAllOrgsV1OK creates GetAllOrgsV1OK with default headers values
func NewGetAllOrgsV1OK() *GetAllOrgsV1OK {

	return &GetAllOrgsV1OK{}
}

// WithPayload adds the payload to the get all orgs v1 o k response
func (o *GetAllOrgsV1OK) WithPayload(payload *model.OrganizationList) *GetAllOrgsV1OK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get all orgs v1 o k response
func (o *GetAllOrgsV1OK) SetPayload(payload *model.OrganizationList) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetAllOrgsV1OK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetAllOrgsV1BadRequestCode is the HTTP code returned for type GetAllOrgsV1BadRequest
const GetAllOrgsV1BadRequestCode int = 400

/*GetAllOrgsV1BadRequest The provided request was invalid.

swagger:response getAllOrgsV1BadRequest
*/
type GetAllOrgsV1BadRequest struct {

	/*
	  In: Body
	*/
	Payload *model.StandardError `json:"body,omitempty"`
}

// NewGetAllOrgsV1BadRequest creates GetAllOrgsV1BadRequest with default headers values
func NewGetAllOrgsV1BadRequest() *GetAllOrgsV1BadRequest {

	return &GetAllOrgsV1BadRequest{}
}

// WithPayload adds the payload to the get all orgs v1 bad request response
func (o *GetAllOrgsV1BadRequest) WithPayload(payload *model.StandardError) *GetAllOrgsV1BadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get all orgs v1 bad request response
func (o *GetAllOrgsV1BadRequest) SetPayload(payload *model.StandardError) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetAllOrgsV1BadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetAllOrgsV1NotFoundCode is the HTTP code returned for type GetAllOrgsV1NotFound
const GetAllOrgsV1NotFoundCode int = 404

/*GetAllOrgsV1NotFound The resource requested does not exist.

swagger:response getAllOrgsV1NotFound
*/
type GetAllOrgsV1NotFound struct {

	/*
	  In: Body
	*/
	Payload *model.StandardError `json:"body,omitempty"`
}

// NewGetAllOrgsV1NotFound creates GetAllOrgsV1NotFound with default headers values
func NewGetAllOrgsV1NotFound() *GetAllOrgsV1NotFound {

	return &GetAllOrgsV1NotFound{}
}

// WithPayload adds the payload to the get all orgs v1 not found response
func (o *GetAllOrgsV1NotFound) WithPayload(payload *model.StandardError) *GetAllOrgsV1NotFound {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get all orgs v1 not found response
func (o *GetAllOrgsV1NotFound) SetPayload(payload *model.StandardError) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetAllOrgsV1NotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetAllOrgsV1InternalServerErrorCode is the HTTP code returned for type GetAllOrgsV1InternalServerError
const GetAllOrgsV1InternalServerErrorCode int = 500

/*GetAllOrgsV1InternalServerError An unexpected system or network error occured.

swagger:response getAllOrgsV1InternalServerError
*/
type GetAllOrgsV1InternalServerError struct {

	/*
	  In: Body
	*/
	Payload *model.StandardError `json:"body,omitempty"`
}

// NewGetAllOrgsV1InternalServerError creates GetAllOrgsV1InternalServerError with default headers values
func NewGetAllOrgsV1InternalServerError() *GetAllOrgsV1InternalServerError {

	return &GetAllOrgsV1InternalServerError{}
}

// WithPayload adds the payload to the get all orgs v1 internal server error response
func (o *GetAllOrgsV1InternalServerError) WithPayload(payload *model.StandardError) *GetAllOrgsV1InternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get all orgs v1 internal server error response
func (o *GetAllOrgsV1InternalServerError) SetPayload(payload *model.StandardError) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetAllOrgsV1InternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
