// Code generated by go-swagger; DO NOT EDIT.

package organization

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"

	"github.com/syllabix/rollpay/backend/api/model"
)

// GetAllOrgsV1HandlerFunc turns a function with the right signature into a get all orgs v1 handler
type GetAllOrgsV1HandlerFunc func(GetAllOrgsV1Params, *model.Principal) middleware.Responder

// Handle executing the request and returning a response
func (fn GetAllOrgsV1HandlerFunc) Handle(params GetAllOrgsV1Params, principal *model.Principal) middleware.Responder {
	return fn(params, principal)
}

// GetAllOrgsV1Handler interface for that can handle valid get all orgs v1 params
type GetAllOrgsV1Handler interface {
	Handle(GetAllOrgsV1Params, *model.Principal) middleware.Responder
}

// NewGetAllOrgsV1 creates a new http.Handler for the get all orgs v1 operation
func NewGetAllOrgsV1(ctx *middleware.Context, handler GetAllOrgsV1Handler) *GetAllOrgsV1 {
	return &GetAllOrgsV1{Context: ctx, Handler: handler}
}

/* GetAllOrgsV1 swagger:route GET /v1/organization Organization getAllOrgsV1

get all organizations

*/
type GetAllOrgsV1 struct {
	Context *middleware.Context
	Handler GetAllOrgsV1Handler
}

func (o *GetAllOrgsV1) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewGetAllOrgsV1Params()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal *model.Principal
	if uprinc != nil {
		principal = uprinc.(*model.Principal) // this is really a model.Principal, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
