// Code generated by go-swagger; DO NOT EDIT.

package operation

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"net/http"
	"strings"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/loads"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/runtime/security"
	"github.com/go-openapi/spec"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"github.com/syllabix/rollpay/backend/api/model"
	"github.com/syllabix/rollpay/backend/api/rest/operation/authorization"
	"github.com/syllabix/rollpay/backend/api/rest/operation/health"
	"github.com/syllabix/rollpay/backend/api/rest/operation/organization"
	"github.com/syllabix/rollpay/backend/api/rest/operation/user"
)

// NewRollpayAPI creates a new Rollpay instance
func NewRollpayAPI(spec *loads.Document) *RollpayAPI {
	return &RollpayAPI{
		handlers:            make(map[string]map[string]http.Handler),
		formats:             strfmt.Default,
		defaultConsumes:     "application/json",
		defaultProduces:     "application/json",
		customConsumers:     make(map[string]runtime.Consumer),
		customProducers:     make(map[string]runtime.Producer),
		PreServerShutdown:   func() {},
		ServerShutdown:      func() {},
		spec:                spec,
		useSwaggerUI:        false,
		ServeError:          errors.ServeError,
		BasicAuthenticator:  security.BasicAuth,
		APIKeyAuthenticator: security.APIKeyAuth,
		BearerAuthenticator: security.BearerAuth,

		JSONConsumer:          runtime.JSONConsumer(),
		MultipartformConsumer: runtime.DiscardConsumer,

		JSONProducer: runtime.JSONProducer(),

		HealthCheckV1Handler: health.CheckV1HandlerFunc(func(params health.CheckV1Params) middleware.Responder {
			return middleware.NotImplemented("operation health.CheckV1 has not yet been implemented")
		}),
		OrganizationCreateOrganizationV1Handler: organization.CreateOrganizationV1HandlerFunc(func(params organization.CreateOrganizationV1Params, principal *model.Principal) middleware.Responder {
			return middleware.NotImplemented("operation organization.CreateOrganizationV1 has not yet been implemented")
		}),
		UserCreateUserV1Handler: user.CreateUserV1HandlerFunc(func(params user.CreateUserV1Params) middleware.Responder {
			return middleware.NotImplemented("operation user.CreateUserV1 has not yet been implemented")
		}),
		OrganizationDeleteOrganizationByIDV1Handler: organization.DeleteOrganizationByIDV1HandlerFunc(func(params organization.DeleteOrganizationByIDV1Params, principal *model.Principal) middleware.Responder {
			return middleware.NotImplemented("operation organization.DeleteOrganizationByIDV1 has not yet been implemented")
		}),
		UserDeleteUserByIDV1Handler: user.DeleteUserByIDV1HandlerFunc(func(params user.DeleteUserByIDV1Params, principal *model.Principal) middleware.Responder {
			return middleware.NotImplemented("operation user.DeleteUserByIDV1 has not yet been implemented")
		}),
		OrganizationGetOrganizationByIDV1Handler: organization.GetOrganizationByIDV1HandlerFunc(func(params organization.GetOrganizationByIDV1Params, principal *model.Principal) middleware.Responder {
			return middleware.NotImplemented("operation organization.GetOrganizationByIDV1 has not yet been implemented")
		}),
		UserGetUserByIDV1Handler: user.GetUserByIDV1HandlerFunc(func(params user.GetUserByIDV1Params, principal *model.Principal) middleware.Responder {
			return middleware.NotImplemented("operation user.GetUserByIDV1 has not yet been implemented")
		}),
		AuthorizationStartPlaidLinkV1Handler: authorization.StartPlaidLinkV1HandlerFunc(func(params authorization.StartPlaidLinkV1Params, principal *model.Principal) middleware.Responder {
			return middleware.NotImplemented("operation authorization.StartPlaidLinkV1 has not yet been implemented")
		}),
		OrganizationUpdateOrganizationByIDV1Handler: organization.UpdateOrganizationByIDV1HandlerFunc(func(params organization.UpdateOrganizationByIDV1Params, principal *model.Principal) middleware.Responder {
			return middleware.NotImplemented("operation organization.UpdateOrganizationByIDV1 has not yet been implemented")
		}),
		UserUpdateUserByIDV1Handler: user.UpdateUserByIDV1HandlerFunc(func(params user.UpdateUserByIDV1Params, principal *model.Principal) middleware.Responder {
			return middleware.NotImplemented("operation user.UpdateUserByIDV1 has not yet been implemented")
		}),

		// Applies when the "Authorization" header is set
		IsAuthenticatedAuth: func(token string) (*model.Principal, error) {
			return nil, errors.NotImplemented("api key auth (isAuthenticated) Authorization from header param [Authorization] has not yet been implemented")
		},
		// default authorizer is authorized meaning no requests are blocked
		APIAuthorizer: security.Authorized(),
	}
}

/*RollpayAPI The restful interface for the Rollpay Service */
type RollpayAPI struct {
	spec            *loads.Document
	context         *middleware.Context
	handlers        map[string]map[string]http.Handler
	formats         strfmt.Registry
	customConsumers map[string]runtime.Consumer
	customProducers map[string]runtime.Producer
	defaultConsumes string
	defaultProduces string
	Middleware      func(middleware.Builder) http.Handler
	useSwaggerUI    bool

	// BasicAuthenticator generates a runtime.Authenticator from the supplied basic auth function.
	// It has a default implementation in the security package, however you can replace it for your particular usage.
	BasicAuthenticator func(security.UserPassAuthentication) runtime.Authenticator

	// APIKeyAuthenticator generates a runtime.Authenticator from the supplied token auth function.
	// It has a default implementation in the security package, however you can replace it for your particular usage.
	APIKeyAuthenticator func(string, string, security.TokenAuthentication) runtime.Authenticator

	// BearerAuthenticator generates a runtime.Authenticator from the supplied bearer token auth function.
	// It has a default implementation in the security package, however you can replace it for your particular usage.
	BearerAuthenticator func(string, security.ScopedTokenAuthentication) runtime.Authenticator

	// JSONConsumer registers a consumer for the following mime types:
	//   - application/json
	JSONConsumer runtime.Consumer
	// MultipartformConsumer registers a consumer for the following mime types:
	//   - multipart/form-data
	MultipartformConsumer runtime.Consumer

	// JSONProducer registers a producer for the following mime types:
	//   - application/json
	JSONProducer runtime.Producer

	// IsAuthenticatedAuth registers a function that takes a token and returns a principal
	// it performs authentication based on an api key Authorization provided in the header
	IsAuthenticatedAuth func(string) (*model.Principal, error)

	// APIAuthorizer provides access control (ACL/RBAC/ABAC) by providing access to the request and authenticated principal
	APIAuthorizer runtime.Authorizer

	// HealthCheckV1Handler sets the operation handler for the check v1 operation
	HealthCheckV1Handler health.CheckV1Handler
	// OrganizationCreateOrganizationV1Handler sets the operation handler for the create organization v1 operation
	OrganizationCreateOrganizationV1Handler organization.CreateOrganizationV1Handler
	// UserCreateUserV1Handler sets the operation handler for the create user v1 operation
	UserCreateUserV1Handler user.CreateUserV1Handler
	// OrganizationDeleteOrganizationByIDV1Handler sets the operation handler for the delete organization by ID v1 operation
	OrganizationDeleteOrganizationByIDV1Handler organization.DeleteOrganizationByIDV1Handler
	// UserDeleteUserByIDV1Handler sets the operation handler for the delete user by ID v1 operation
	UserDeleteUserByIDV1Handler user.DeleteUserByIDV1Handler
	// OrganizationGetOrganizationByIDV1Handler sets the operation handler for the get organization by ID v1 operation
	OrganizationGetOrganizationByIDV1Handler organization.GetOrganizationByIDV1Handler
	// UserGetUserByIDV1Handler sets the operation handler for the get user by ID v1 operation
	UserGetUserByIDV1Handler user.GetUserByIDV1Handler
	// AuthorizationStartPlaidLinkV1Handler sets the operation handler for the start plaid link v1 operation
	AuthorizationStartPlaidLinkV1Handler authorization.StartPlaidLinkV1Handler
	// OrganizationUpdateOrganizationByIDV1Handler sets the operation handler for the update organization by ID v1 operation
	OrganizationUpdateOrganizationByIDV1Handler organization.UpdateOrganizationByIDV1Handler
	// UserUpdateUserByIDV1Handler sets the operation handler for the update user by ID v1 operation
	UserUpdateUserByIDV1Handler user.UpdateUserByIDV1Handler

	// ServeError is called when an error is received, there is a default handler
	// but you can set your own with this
	ServeError func(http.ResponseWriter, *http.Request, error)

	// PreServerShutdown is called before the HTTP(S) server is shutdown
	// This allows for custom functions to get executed before the HTTP(S) server stops accepting traffic
	PreServerShutdown func()

	// ServerShutdown is called when the HTTP(S) server is shut down and done
	// handling all active connections and does not accept connections any more
	ServerShutdown func()

	// Custom command line argument groups with their descriptions
	CommandLineOptionsGroups []swag.CommandLineOptionsGroup

	// User defined logger function.
	Logger func(string, ...interface{})
}

// UseRedoc for documentation at /docs
func (o *RollpayAPI) UseRedoc() {
	o.useSwaggerUI = false
}

// UseSwaggerUI for documentation at /docs
func (o *RollpayAPI) UseSwaggerUI() {
	o.useSwaggerUI = true
}

// SetDefaultProduces sets the default produces media type
func (o *RollpayAPI) SetDefaultProduces(mediaType string) {
	o.defaultProduces = mediaType
}

// SetDefaultConsumes returns the default consumes media type
func (o *RollpayAPI) SetDefaultConsumes(mediaType string) {
	o.defaultConsumes = mediaType
}

// SetSpec sets a spec that will be served for the clients.
func (o *RollpayAPI) SetSpec(spec *loads.Document) {
	o.spec = spec
}

// DefaultProduces returns the default produces media type
func (o *RollpayAPI) DefaultProduces() string {
	return o.defaultProduces
}

// DefaultConsumes returns the default consumes media type
func (o *RollpayAPI) DefaultConsumes() string {
	return o.defaultConsumes
}

// Formats returns the registered string formats
func (o *RollpayAPI) Formats() strfmt.Registry {
	return o.formats
}

// RegisterFormat registers a custom format validator
func (o *RollpayAPI) RegisterFormat(name string, format strfmt.Format, validator strfmt.Validator) {
	o.formats.Add(name, format, validator)
}

// Validate validates the registrations in the RollpayAPI
func (o *RollpayAPI) Validate() error {
	var unregistered []string

	if o.JSONConsumer == nil {
		unregistered = append(unregistered, "JSONConsumer")
	}
	if o.MultipartformConsumer == nil {
		unregistered = append(unregistered, "MultipartformConsumer")
	}

	if o.JSONProducer == nil {
		unregistered = append(unregistered, "JSONProducer")
	}

	if o.IsAuthenticatedAuth == nil {
		unregistered = append(unregistered, "AuthorizationAuth")
	}

	if o.HealthCheckV1Handler == nil {
		unregistered = append(unregistered, "health.CheckV1Handler")
	}
	if o.OrganizationCreateOrganizationV1Handler == nil {
		unregistered = append(unregistered, "organization.CreateOrganizationV1Handler")
	}
	if o.UserCreateUserV1Handler == nil {
		unregistered = append(unregistered, "user.CreateUserV1Handler")
	}
	if o.OrganizationDeleteOrganizationByIDV1Handler == nil {
		unregistered = append(unregistered, "organization.DeleteOrganizationByIDV1Handler")
	}
	if o.UserDeleteUserByIDV1Handler == nil {
		unregistered = append(unregistered, "user.DeleteUserByIDV1Handler")
	}
	if o.OrganizationGetOrganizationByIDV1Handler == nil {
		unregistered = append(unregistered, "organization.GetOrganizationByIDV1Handler")
	}
	if o.UserGetUserByIDV1Handler == nil {
		unregistered = append(unregistered, "user.GetUserByIDV1Handler")
	}
	if o.AuthorizationStartPlaidLinkV1Handler == nil {
		unregistered = append(unregistered, "authorization.StartPlaidLinkV1Handler")
	}
	if o.OrganizationUpdateOrganizationByIDV1Handler == nil {
		unregistered = append(unregistered, "organization.UpdateOrganizationByIDV1Handler")
	}
	if o.UserUpdateUserByIDV1Handler == nil {
		unregistered = append(unregistered, "user.UpdateUserByIDV1Handler")
	}

	if len(unregistered) > 0 {
		return fmt.Errorf("missing registration: %s", strings.Join(unregistered, ", "))
	}

	return nil
}

// ServeErrorFor gets a error handler for a given operation id
func (o *RollpayAPI) ServeErrorFor(operationID string) func(http.ResponseWriter, *http.Request, error) {
	return o.ServeError
}

// AuthenticatorsFor gets the authenticators for the specified security schemes
func (o *RollpayAPI) AuthenticatorsFor(schemes map[string]spec.SecurityScheme) map[string]runtime.Authenticator {
	result := make(map[string]runtime.Authenticator)
	for name := range schemes {
		switch name {
		case "isAuthenticated":
			scheme := schemes[name]
			result[name] = o.APIKeyAuthenticator(scheme.Name, scheme.In, func(token string) (interface{}, error) {
				return o.IsAuthenticatedAuth(token)
			})

		}
	}
	return result
}

// Authorizer returns the registered authorizer
func (o *RollpayAPI) Authorizer() runtime.Authorizer {
	return o.APIAuthorizer
}

// ConsumersFor gets the consumers for the specified media types.
// MIME type parameters are ignored here.
func (o *RollpayAPI) ConsumersFor(mediaTypes []string) map[string]runtime.Consumer {
	result := make(map[string]runtime.Consumer, len(mediaTypes))
	for _, mt := range mediaTypes {
		switch mt {
		case "application/json":
			result["application/json"] = o.JSONConsumer
		case "multipart/form-data":
			result["multipart/form-data"] = o.MultipartformConsumer
		}

		if c, ok := o.customConsumers[mt]; ok {
			result[mt] = c
		}
	}
	return result
}

// ProducersFor gets the producers for the specified media types.
// MIME type parameters are ignored here.
func (o *RollpayAPI) ProducersFor(mediaTypes []string) map[string]runtime.Producer {
	result := make(map[string]runtime.Producer, len(mediaTypes))
	for _, mt := range mediaTypes {
		switch mt {
		case "application/json":
			result["application/json"] = o.JSONProducer
		}

		if p, ok := o.customProducers[mt]; ok {
			result[mt] = p
		}
	}
	return result
}

// HandlerFor gets a http.Handler for the provided operation method and path
func (o *RollpayAPI) HandlerFor(method, path string) (http.Handler, bool) {
	if o.handlers == nil {
		return nil, false
	}
	um := strings.ToUpper(method)
	if _, ok := o.handlers[um]; !ok {
		return nil, false
	}
	if path == "/" {
		path = ""
	}
	h, ok := o.handlers[um][path]
	return h, ok
}

// Context returns the middleware context for the rollpay API
func (o *RollpayAPI) Context() *middleware.Context {
	if o.context == nil {
		o.context = middleware.NewRoutableContext(o.spec, o, nil)
	}

	return o.context
}

func (o *RollpayAPI) initHandlerCache() {
	o.Context() // don't care about the result, just that the initialization happened
	if o.handlers == nil {
		o.handlers = make(map[string]map[string]http.Handler)
	}

	if o.handlers["GET"] == nil {
		o.handlers["GET"] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/v1/healthz"] = health.NewCheckV1(o.context, o.HealthCheckV1Handler)
	if o.handlers["POST"] == nil {
		o.handlers["POST"] = make(map[string]http.Handler)
	}
	o.handlers["POST"]["/v1/organization"] = organization.NewCreateOrganizationV1(o.context, o.OrganizationCreateOrganizationV1Handler)
	if o.handlers["POST"] == nil {
		o.handlers["POST"] = make(map[string]http.Handler)
	}
	o.handlers["POST"]["/v1/user"] = user.NewCreateUserV1(o.context, o.UserCreateUserV1Handler)
	if o.handlers["DELETE"] == nil {
		o.handlers["DELETE"] = make(map[string]http.Handler)
	}
	o.handlers["DELETE"]["/v1/organization/{id}"] = organization.NewDeleteOrganizationByIDV1(o.context, o.OrganizationDeleteOrganizationByIDV1Handler)
	if o.handlers["DELETE"] == nil {
		o.handlers["DELETE"] = make(map[string]http.Handler)
	}
	o.handlers["DELETE"]["/v1/user/{id}"] = user.NewDeleteUserByIDV1(o.context, o.UserDeleteUserByIDV1Handler)
	if o.handlers["GET"] == nil {
		o.handlers["GET"] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/v1/organization/{id}"] = organization.NewGetOrganizationByIDV1(o.context, o.OrganizationGetOrganizationByIDV1Handler)
	if o.handlers["GET"] == nil {
		o.handlers["GET"] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/v1/user/{id}"] = user.NewGetUserByIDV1(o.context, o.UserGetUserByIDV1Handler)
	if o.handlers["POST"] == nil {
		o.handlers["POST"] = make(map[string]http.Handler)
	}
	o.handlers["POST"]["/v1/auth/link-token"] = authorization.NewStartPlaidLinkV1(o.context, o.AuthorizationStartPlaidLinkV1Handler)
	if o.handlers["PUT"] == nil {
		o.handlers["PUT"] = make(map[string]http.Handler)
	}
	o.handlers["PUT"]["/v1/organization/{id}"] = organization.NewUpdateOrganizationByIDV1(o.context, o.OrganizationUpdateOrganizationByIDV1Handler)
	if o.handlers["PUT"] == nil {
		o.handlers["PUT"] = make(map[string]http.Handler)
	}
	o.handlers["PUT"]["/v1/user/{id}"] = user.NewUpdateUserByIDV1(o.context, o.UserUpdateUserByIDV1Handler)
}

// Serve creates a http handler to serve the API over HTTP
// can be used directly in http.ListenAndServe(":8000", api.Serve(nil))
func (o *RollpayAPI) Serve(builder middleware.Builder) http.Handler {
	o.Init()

	if o.Middleware != nil {
		return o.Middleware(builder)
	}
	if o.useSwaggerUI {
		return o.context.APIHandlerSwaggerUI(builder)
	}
	return o.context.APIHandler(builder)
}

// Init allows you to just initialize the handler cache, you can then recompose the middleware as you see fit
func (o *RollpayAPI) Init() {
	if len(o.handlers) == 0 {
		o.initHandlerCache()
	}
}

// RegisterConsumer allows you to add (or override) a consumer for a media type.
func (o *RollpayAPI) RegisterConsumer(mediaType string, consumer runtime.Consumer) {
	o.customConsumers[mediaType] = consumer
}

// RegisterProducer allows you to add (or override) a producer for a media type.
func (o *RollpayAPI) RegisterProducer(mediaType string, producer runtime.Producer) {
	o.customProducers[mediaType] = producer
}

// AddMiddlewareFor adds a http middleware to existing handler
func (o *RollpayAPI) AddMiddlewareFor(method, path string, builder middleware.Builder) {
	um := strings.ToUpper(method)
	if path == "/" {
		path = ""
	}
	o.Init()
	if h, ok := o.handlers[um][path]; ok {
		o.handlers[method][path] = builder(h)
	}
}
